apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kubeflow
resources:
- cluster-role-binding.yaml
- cluster-role.yaml
- deployment.yaml
- service-account.yaml
- service.yaml
commonLabels:
  kustomize.component: pytorch-operator
images:
- name: gcr.io/kubeflow-images-public/pytorch-operator
  newName: gcr.io/kubeflow-images-public/pytorch-operator
<<<<<<< HEAD
<<<<<<< HEAD
  newTag: v1.0.0-g047cf0f
=======
  newTag: vmaster-gd596e904
>>>>>>> 0dd7b24f049aaff540231bf73fe153c2397be890
=======
  newTag: vmaster-g518f9c76
>>>>>>> upstream/master
