apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeRouter
metadata:
<<<<<<< HEAD
<<<<<<< HEAD
  name: name # {"$kpt-set":"name"}
spec:
  description: Router to allow outbound internet access
  region: REGION # {"$kpt-set":"gcloud.compute.region"}
  networkRef:
    name: name # {"$kpt-set":"name"}
=======
  name: name # {"type":"string","x-kustomize":{"setter":{"name":"name","value":"name"}}}
=======
  name: name # {"$kpt-set":"name"}
>>>>>>> upstream/master
spec:
  description: Router to allow outbound internet access
  region: REGION # {"$kpt-set":"gcloud.compute.region"}
  networkRef:
<<<<<<< HEAD
    name: name # {"type":"string","x-kustomize":{"setter":{"name":"name","value":"name"}}}
>>>>>>> 0dd7b24f049aaff540231bf73fe153c2397be890
=======
    name: name # {"$kpt-set":"name"}
>>>>>>> upstream/master
---
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeRouterNAT
metadata:
<<<<<<< HEAD
<<<<<<< HEAD
  name: name # {"$kpt-set":"name"}
spec:
  region: REGION # {"$kpt-set":"gcloud.compute.region"}
  routerRef:
    name: name # {"$kpt-set":"name"}
=======
  name: name # {"type":"string","x-kustomize":{"setter":{"name":"name","value":"name"}}}
=======
  name: name # {"$kpt-set":"name"}
>>>>>>> upstream/master
spec:
  region: REGION # {"$kpt-set":"gcloud.compute.region"}
  routerRef:
<<<<<<< HEAD
    name: name # {"type":"string","x-kustomize":{"setter":{"name":"name","value":"name"}}}
>>>>>>> 0dd7b24f049aaff540231bf73fe153c2397be890
=======
    name: name # {"$kpt-set":"name"}
>>>>>>> upstream/master
  natIpAllocateOption: AUTO_ONLY
  sourceSubnetworkIpRangesToNat: ALL_SUBNETWORKS_ALL_IP_RANGES
