apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeAddress
metadata:
<<<<<<< HEAD
<<<<<<< HEAD
  name: name-ip # {"$kpt-set":"name-ip"}
=======
  name: name-ip # {"type":"string","x-kustomize":{"setBy":"kpt","partialSetters":[{"name":"name","value":"name"}]}}
>>>>>>> 0dd7b24f049aaff540231bf73fe153c2397be890
=======
  name: name-ip # {"$kpt-set":"name-ip"}
>>>>>>> upstream/master
  labels:
    label-one: "value-one"
spec:
  addressType: EXTERNAL
  description: Static IP for Kubeflow ingress.
  location: global
  ipVersion: IPV4
