apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: istio-system
resources:
<<<<<<< HEAD
- ../../../../istio-1-3-1/cluster-local-gateway-1-3-1/base
=======
- ../../../../istio-1-3-1/cluster-local-gateway-1-3-1/base_v3
>>>>>>> upstream/master
