# This file configures the workflows to trigger in our Prow jobs.
# see https://github.com/kubeflow/testing/blob/master/py/kubeflow/testing/run_e2e_workflow.py
python_paths:
  # Need to place kubeflow/testing in front of kubeflow/testing so that the package can
  # be correctly located.
  - kubeflow/testing/py
  - kubeflow/kfctl/py
workflows:
  - app_dir: kubeflow/manifests/tests/workflows
    component: workflows
    name: unit
    job_types:
      - presubmit
      - postsubmit
<<<<<<< HEAD
      - periodic    

  # Run the e2e tests to ensure that changes to manifests don't break deployments.
  - py_func: kubeflow.kfctl.testing.ci.kfctl_e2e_workflow.create_workflow
    name: e2e
    job_types:
      - presubmit
      - postsubmit
      - periodic    
    kwargs:
      use_basic_auth: false
      # Run build and then apply rather than just apply
      build_and_apply: true
      # test_endpoint flag is actually deprecated; we use pytest annotations to skip on
      # presubmit.
      test_endpoint: true
      # The path for the config should depend on the commit we are testing manifests on.
      # so we use the local path which will be checked out to the correct commit
      config_path: "{srcrootdir}/kubeflow/manifests/kfdef/kfctl_gcp_iap.yaml"
=======
      - periodic
<<<<<<< HEAD
>>>>>>> 0dd7b24f049aaff540231bf73fe153c2397be890
=======
  - py_func: kubeflow.kfctl.testing.ci.kfctl_e2e_workflow.create_workflow
    name: e2e
    job_types:
      - presubmit
      - postsubmit
      - periodic
    include_dirs:
      - admission-webhook/*
      - application/*
      - argo/*
      - aws/*
      - cert-manager/*
      - common/
      - default-install/*
      - dex-auth/*
      - experimental/*
      - istio-1-3-1/*
      - istio/*
      - jupyter/*
      - katib/*
      - kfdef/kfctl_istio_dex*
      - kfserving/*
      - knative/*
      - kubebench/*
      - kubeflow-roles/*
      - metacontroller/*
      - metadata/*
      - mpi-job/*
      - mxnet-job/*
      - namespaces/*
      - pipeline/*
      - profiles/*
      - pytorch-job/*
      - seldon/*
      - spark/*
      - stacks/*
      - tektoncd/*
      - tf-training/*
      - xgboost-job/*
    kwargs:
      build_and_apply: false
      config_path: https://raw.githubusercontent.com/kubeflow/manifests/master/kfdef/kfctl_istio_dex.yaml

  ####################################### AWS Specific Tests
  - py_func: kubeflow.kfctl.testing.ci.kfctl_e2e_workflow.create_workflow
    name: aws-default
    job_types:
      - periodic
    kwargs:
      build_and_apply: false
      config_path: https://raw.githubusercontent.com/kubeflow/manifests/master/kfdef/kfctl_aws.yaml
      
  - py_func: kubeflow.kfctl.testing.ci.kfctl_e2e_workflow.create_workflow
    name: aws-1-15
    job_types:
      - periodic
    kwargs:
      build_and_apply: false
      config_path: https://raw.githubusercontent.com/kubeflow/manifests/master/kfdef/kfctl_aws.yaml
      eks_cluster_version: "1.15"
    
  - py_func: kubeflow.kfctl.testing.ci.kfctl_e2e_workflow.create_workflow
    name: aws-1-16
    job_types:
      - periodic
    kwargs:
      build_and_apply: false
      config_path: https://raw.githubusercontent.com/kubeflow/manifests/master/kfdef/kfctl_aws.yaml
      eks_cluster_version: "1.16"  

  - py_func: kubeflow.kfctl.testing.ci.kfctl_e2e_workflow.create_workflow
    name: aws-1-17
    job_types:
      - periodic
    kwargs:
      build_and_apply: false
      config_path: https://raw.githubusercontent.com/kubeflow/manifests/master/kfdef/kfctl_aws.yaml
      eks_cluster_version: "1.17"
  
  - py_func: kubeflow.kfctl.testing.ci.kfctl_e2e_workflow.create_workflow
    name: aws-1-18
    job_types:
      - periodic
    kwargs:
      build_and_apply: false
      config_path: https://raw.githubusercontent.com/kubeflow/manifests/master/kfdef/kfctl_aws.yaml
      eks_cluster_version: "1.18"
>>>>>>> upstream/master
