apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
<<<<<<< HEAD
    eventing.knative.dev/release: "v0.11.0"
=======
    eventing.knative.dev/release: v0.14.2
>>>>>>> upstream/master
  name: eventing-controller
  namespace: knative-eventing
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
<<<<<<< HEAD
    eventing.knative.dev/release: "v0.11.0"
  name: eventing-webhook
=======
    eventing.knative.dev/release: v0.14.2
  name: pingsource-jobrunner
>>>>>>> upstream/master
  namespace: knative-eventing
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
<<<<<<< HEAD
    eventing.knative.dev/release: "v0.11.0"
  name: eventing-source-controller
=======
    eventing.knative.dev/release: v0.14.2
  name: eventing-webhook
>>>>>>> upstream/master
  namespace: knative-eventing
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
<<<<<<< HEAD
    eventing.knative.dev/release: "v0.11.0"
=======
    eventing.knative.dev/release: v0.14.2
>>>>>>> upstream/master
  name: imc-controller
  namespace: knative-eventing
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
<<<<<<< HEAD
    eventing.knative.dev/release: "v0.11.0"
=======
    eventing.knative.dev/release: v0.14.2
>>>>>>> upstream/master
  name: imc-dispatcher
  namespace: knative-eventing
