apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  labels:
<<<<<<< HEAD
    eventing.knative.dev/release: "v0.11.0"
=======
    eventing.knative.dev/release: v0.14.2
>>>>>>> upstream/master
  name: webhook.eventing.knative.dev
webhooks:
- admissionReviewVersions:
  - v1beta1
  clientConfig:
    service:
      name: eventing-webhook
      namespace: knative-eventing
  failurePolicy: Fail
  name: webhook.eventing.knative.dev
<<<<<<< HEAD
=======
  sideEffects: None
>>>>>>> upstream/master
---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  labels:
<<<<<<< HEAD
    eventing.knative.dev/release: "v0.11.0"
=======
    eventing.knative.dev/release: v0.14.2
>>>>>>> upstream/master
  name: validation.webhook.eventing.knative.dev
webhooks:
- admissionReviewVersions:
  - v1beta1
  clientConfig:
    service:
      name: eventing-webhook
      namespace: knative-eventing
  failurePolicy: Fail
  name: validation.webhook.eventing.knative.dev
<<<<<<< HEAD
=======
  sideEffects: None
>>>>>>> upstream/master
---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  labels:
<<<<<<< HEAD
    serving.knative.dev/release: devel
=======
    eventing.knative.dev/release: v0.14.2
>>>>>>> upstream/master
  name: config.webhook.eventing.knative.dev
webhooks:
- admissionReviewVersions:
  - v1beta1
  clientConfig:
    service:
      name: eventing-webhook
      namespace: knative-eventing
  failurePolicy: Fail
  name: config.webhook.eventing.knative.dev
  namespaceSelector:
    matchExpressions:
    - key: eventing.knative.dev/release
      operator: Exists
<<<<<<< HEAD
=======
  sideEffects: None
>>>>>>> upstream/master
---
apiVersion: admissionregistration.k8s.io/v1beta1
kind: MutatingWebhookConfiguration
metadata:
  labels:
<<<<<<< HEAD
    eventing.knative.dev/release: "v0.11.0"
=======
    eventing.knative.dev/release: v0.14.2
>>>>>>> upstream/master
  name: sinkbindings.webhook.sources.knative.dev
webhooks:
- admissionReviewVersions:
  - v1beta1
  clientConfig:
    service:
      name: eventing-webhook
      namespace: knative-eventing
  failurePolicy: Fail
  name: sinkbindings.webhook.sources.knative.dev
<<<<<<< HEAD
=======
  sideEffects: None
>>>>>>> upstream/master
