apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kubeflow
resources:
  - ../../admission-webhook/webhook/v3
  - ../../common/centraldashboard/overlays/stacks
  - ../../kubeflow-roles/base
  - application/jupyter-web-app
  - application/notebook-controller
  - application/profiles
<<<<<<< HEAD
<<<<<<< HEAD
  - ../../pipeline/minio/installs/ibm
  - ../../pipeline/mysql/installs/ibm
  - ../../pipeline/installs/generic
  - ../../argo/base_v3
  - application/metadata
=======
  - ../../argo/base_v3
  - ../../pipeline/api-service/overlays/application
  - ../../pipeline/minio/installs/ibm
  - ../../pipeline/mysql/installs/ibm
  - ../../pipeline/persistent-agent/overlays/application
  - ../../pipeline/pipelines-runner/overlays/application
  - application/pipelines-ui
  - ../../pipeline/pipelines-viewer/overlays/application
  - ../../pipeline/scheduledworkflow/overlays/application
  - ../../pipeline/pipeline-visualization-service/overlays/application
>>>>>>> 0dd7b24f049aaff540231bf73fe153c2397be890
=======
  - ../../pipeline/minio/installs/ibm
  - ../../pipeline/mysql/installs/ibm
  - ../../pipeline/installs/generic
  - ../../argo/base_v3
  - application/metadata
>>>>>>> upstream/master
  - ../../pytorch-job/pytorch-job-crds/overlays/application
  - ../../pytorch-job/pytorch-operator/overlays/application
  - ../../tf-training/tf-job-crds/overlays/application
  - ../../tf-training/tf-job-operator/overlays/application
  - ../../katib/installs/katib-standalone-ibm
  - ../../seldon/seldon-core-operator/overlays/application
configMapGenerator:
- name: pipeline-mysql-parameters
  behavior: merge
  literals:
  - mysqlPvcName=mysql-pv-claim
- name: pipeline-minio-parameters
  behavior: merge
  literals:
  - minioPvcName=minio-pv-claim
- name: workflow-controller-parameters
  behavior: merge
  literals:
  - containerRuntimeExecutor=pns
- name: profiles-config
  behavior: merge
  literals:
  - admin=example@kubeflow.org
vars:
# We need to define vars at the top level otherwise we will get
# conflicts. 
- fieldref:
    fieldpath: metadata.namespace
  name: katib-ui-namespace
  objref:
    kind: Service
    name: katib-ui
    apiVersion: v1
