apiVersion: apps/v1
kind: Deployment
metadata:
  name: kfserving-ingressgateway
spec:
  template:
    spec:
      containers:
      - name: istio-proxy
        resources:
          requests:
            cpu: 10m
            memory: 40Mi
          limits:
            cpu: 100m
            memory: 128Mi
        