apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
  labels:
    app: minio
spec:
  selector:
    matchLabels:
      app: minio
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
      - args:
        - server
        - /data
        env:
        - name: MINIO_ACCESS_KEY
<<<<<<< HEAD
<<<<<<< HEAD
=======
>>>>>>> upstream/master
          valueFrom:
            secretKeyRef:
              name: mlpipeline-minio-artifact
              key: accesskey
<<<<<<< HEAD
        - name: MINIO_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: mlpipeline-minio-artifact
              key: secretkey
=======
          value: minio
        - name: MINIO_SECRET_KEY
          value: minio123
>>>>>>> 0dd7b24f049aaff540231bf73fe153c2397be890
=======
        - name: MINIO_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: mlpipeline-minio-artifact
              key: secretkey
>>>>>>> upstream/master
        image: gcr.io/ml-pipeline/minio:RELEASE.2019-08-14T20-37-41Z-license-compliance
        name: minio
        ports:
        - containerPort: 9000
        volumeMounts:
        - mountPath: /data
          name: data
          subPath: minio
      volumes:
      - name: data
        persistentVolumeClaim:
<<<<<<< HEAD
<<<<<<< HEAD
          claimName: minio-pvc
=======
          claimName: minio-pvc
>>>>>>> 0dd7b24f049aaff540231bf73fe153c2397be890
=======
          claimName: minio-pvc
>>>>>>> upstream/master
