apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
  - ../katib-standalone
patchesStrategicMerge:
  - ../../katib-controller/overlays/ibm-storage-config/katib-mysql-deployment.yaml
  - ../../katib-controller/overlays/katib-cert-injection/katib-cert-injection.yaml
images:
  - name: mysql
    newTag: "5.6"
    newName: mysql
