apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-pipeline-visualizationserver
spec:
  template:
    spec:
      containers:
      - name: ml-pipeline-visualizationserver
        resources:
          requests:
            cpu: 20m
            memory: 400Mi
          limits:
            cpu: 1
            memory: 4Gi