apiVersion: apps/v1
kind: Deployment
metadata:
  name: katib-db-manager
spec:
  template:
    spec:
      containers:
      - name: katib-db-manager
        resources:
          requests:
            cpu: 20m
            memory: 100Mi
          limits:
            cpu: 1
            memory: 2Gi