apiVersion: apps/v1
kind: Deployment
metadata:
  name: katib-mysql
spec:
  template:
    spec:
      containers:
      - name: katib-mysql
        resources:
          requests:
            cpu: 1
            memory: 2Gi
          limits:
            cpu: 1
            memory: 4Gi