apiVersion: apps/v1
kind: Deployment
metadata:
  name: katib-controller
spec:
  template:
    spec:
      containers:
      - name: katib-controller
        resources:
          requests:
            cpu: 30m
            memory: 400Mi
          limits:
            cpu: 1
            memory: 4Gi