apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../base
patchesStrategicMerge:
- katib-controller-deployment.yaml
- katib-db-manager-deployment.yaml
- katib-mysql-deployment.yaml
- katib-ui-deployment.yaml
