apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- metadata-writer-deployment.yaml
- metadata-writer-role.yaml
- metadata-writer-rolebinding.yaml
- metadata-writer-sa.yaml
images:
- name: gcr.io/ml-pipeline/metadata-writer
<<<<<<< HEAD
  newTag: 1.0.0
=======
  newTag: 1.0.4
>>>>>>> upstream/master
