apiVersion: apps/v1
kind: Deployment
metadata:
  name: metadata-envoy-deployment
  labels:
    component: metadata-envoy
spec:
  replicas: 1
  selector:
    matchLabels:
      component: metadata-envoy
  template:
    metadata:
      labels:
        component: metadata-envoy
    spec:
      containers:
      - name: container
<<<<<<< HEAD
<<<<<<< HEAD
        image: gcr.io/ml-pipeline/metadata-envoy:dummy
=======
        image: gcr.io/ml-pipeline/envoy:metadata-grpc
>>>>>>> 0dd7b24f049aaff540231bf73fe153c2397be890
=======
        image: gcr.io/ml-pipeline/metadata-envoy:dummy
>>>>>>> upstream/master
        ports:
        - name: md-envoy
          containerPort: 9090
        - name: envoy-admin
          containerPort: 9901
