apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
spec:
  template:
    spec:
      containers:
      - name: admission-webhook
        resources:
          requests:
            cpu: 20m
            memory: 20Mi
          limits:
            cpu: 1
            memory: 200Mi