apiVersion: apps/v1
kind: Deployment
metadata:
  name: envoy-deployment
spec:
  template:
    spec:
      containers:
      - name: container
        resources:
          requests:
            cpu: 20m
            memory: 150Mi
          limits:
            cpu: 1
            memory: 1.5Gi