namespace: kubeflow
resources:
  - certificate.yaml
  - katib-cert-generator-rbac.yaml
  - katib-cert-generator.yaml
  - katib-configmap.yaml
  - katib-controller-deployment.yaml
  - katib-controller-rbac.yaml
  - katib-controller-secret.yaml
  - katib-controller-service.yaml
  - katib-mysql-deployment.yaml
  - katib-mysql-pvc.yaml
  - katib-mysql-secret.yaml
  - katib-mysql-service.yaml
  - katib-db-manager-deployment.yaml
  - katib-db-manager-service.yaml
  - katib-ui-deployment.yaml
  - katib-ui-rbac.yaml
  - katib-ui-service.yaml
  - katib-webhooks.yaml
  - trial-template-configmap.yaml
configMapGenerator:
  - name: katib-parameters
    envs:
      - params.env
generatorOptions:
  disableNameSuffixHash: true
images:
  - name: docker.io/kubeflowkatib/katib-controller
    newTag: v0.11.0
    newName: docker.io/kubeflowkatib/katib-controller
  - name: docker.io/kubeflowkatib/katib-db-manager
    newTag: v0.11.0
    newName: docker.io/kubeflowkatib/katib-db-manager
  - name: docker.io/kubeflowkatib/katib-ui
    newTag: v0.11.0
    newName: docker.io/kubeflowkatib/katib-ui
  - name: mysql
    newTag: "8"
    newName: mysql
  - name: docker.io/kubeflowkatib/cert-generator
    newName: docker.io/kubeflowkatib/cert-generator
    newTag: v0.11.0
vars:
  - name: clusterDomain
    objref:
      kind: ConfigMap
      name: katib-parameters
      apiVersion: v1
    fieldref:
      fieldpath: data.clusterDomain
  - name: katib-ui-namespace
    objref:
      kind: Service
      name: katib-ui
      apiVersion: v1
    fieldref:
      fieldpath: metadata.namespace
  - name: KATIB_NAMESPACE
    objref:
      apiVersion: v1
      kind: Service
      name: katib-controller
    fieldref:
      fieldPath: metadata.namespace
  - name: KATIB_SERVICE_NAME
    objref:
      apiVersion: v1
      kind: Service
      name: katib-controller 
    fieldref:
      fieldPath: metadata.name
  - name: KATIB_CERT_NAME
    objref:
      kind: Certificate
      group: cert-manager.io
      version: v1alpha2
      name: katib-webhook-cert
    fieldref:
      fieldpath: metadata.name   
configurations:
  - params.yaml
