varReference:
  - path: data/config
    kind: ConfigMap
  - path: data/config
    kind: Deployment
  - path: metadata/annotations/getambassador.io\/config
    kind: Service
  - path: spec/http/route/destination/host
    kind: VirtualService
  - path: spec/commonName
    kind: Certificate
  - path: spec/dnsNames
    kind: Certificate
  - path: spec/issuerRef/name
    kind: Certificate
  - path: metadata/annotations
    kind: MutatingWebhookConfiguration
  - path: metadata/annotations
    kind: ValidatingWebhookConfiguration
nameReference:
  - kind: Issuer
    group: cert-manager.io
    fieldSpecs:
    - kind: Certificate
      group: cert-manager.io
      path: spec/issuerRef/name  
