apiVersion: apps/v1
kind: Deployment
metadata:
  name: cert-manager-cainjector
spec:
  template:
    spec:
      containers:
      - name: cainjector
        resources:
          requests:
            cpu: 20m
            memory: 200Mi
          limits:
            cpu: 1
            memory: 2Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cert-manager
spec:
  template:
    spec:
      containers:
      - name: cert-manager
        resources:
          requests:
            cpu: 10m
            memory: 32Mi
          limits:
            cpu: 1
            memory: 320Mi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cert-manager-webhook
spec:
  template:
    spec:
      containers:
      - name: cert-manager
        resources:
          requests:
            cpu: 20m
            memory: 20Mi
          limits:
            cpu: 1
            memory: 200Mi
        