apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-pipeline
spec:
  template:
    spec:
      containers:
      - name: ml-pipeline-api-server
        resources:
          requests:
            cpu: 20m
            memory: 200Mi
          limits:
            cpu: 1
            memory: 2Gi