apiVersion: apps/v1
kind: Deployment
metadata:
  name: sparkoperator
spec:
  template:
    spec:
      containers:
      - name: sparkoperator
        resources:
          requests:
            cpu: 20m
            memory: 2Gi
          limits:
            cpu: 1
            memory: 4Gi