apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    serving.knative.dev/release: "v0.11.1"
  name: activator
  namespace: knative-serving
spec:
  template:
    spec:
      containers:
      - name: activator
        resources:
          requests:
            cpu: 400m
            memory: 188Mi
          limits:
            cpu: 3
            memory: 1624Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    autoscaling.knative.dev/autoscaler-provider: hpa
    serving.knative.dev/release: "v0.11.1"
  name: autoscaler-hpa
  namespace: knative-serving
spec:
  template:
    spec:
      containers:
      - name: autoscaler-hpa
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 1
            memory: 1000Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    serving.knative.dev/release: "v0.11.1"
  name: autoscaler
  namespace: knative-serving
spec:
  template:
    spec:
      containers:
      - name: autoscaler
        resources:
          requests:
            cpu: 130m
            memory: 168Mi
          limits:
            cpu: 2300m
            memory: 1424Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    networking.knative.dev/ingress-provider: istio
    serving.knative.dev/release: "v0.11.1"
  name: networking-istio
  namespace: knative-serving
spec:
  template:
    spec:
      containers:
      - name: networking-istio
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 1
            memory: 1000Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    serving.knative.dev/release: "v0.11.1"
  name: webhook
  name: webhook
  namespace: knative-serving
spec:
  template:
    spec:
      containers:
      - name: webhook
        resources:
          requests:
            cpu: 20m
            memory: 20Mi
          limits:
            cpu: 200m
            memory: 200Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    serving.knative.dev/release: "v0.11.1"
  name: controller
  namespace: knative-serving
spec:
  template:
    spec:
      containers:
      - name: controller
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 1
            memory: 1000Mi