apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
spec:
  template:
    spec:
      containers:
      - name: minio
        resources:
          requests:
            cpu: 20m
            memory: 100Mi
          limits:
            cpu: 1
            memory: 1Gi