apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  template:
    spec:
      containers:
      - name: mysql
        resources:
          requests:
            cpu: 100m
            memory: 2Gi
          limits:
            cpu: 1
            memory: 4Gi