bases:
- ../../base
patchesStrategicMerge:
- ingress.yaml
configMapGenerator:
- name: istio-ingress-config
  behavior: merge
<<<<<<< HEAD
  env: params.env
=======
  envs:
  - params.env
>>>>>>> 0dd7b24f049aaff540231bf73fe153c2397be890
generatorOptions:
  disableNameSuffixHash: true
vars:
- name: certArn
  objref:
    kind: ConfigMap
    name: istio-ingress-config
    apiVersion: v1
  fieldref:
    fieldpath: data.certArn
- name: hostname
  objref:
    kind: ConfigMap
    name: istio-ingress-config
    apiVersion: v1
  fieldref:
    fieldpath: data.hostname
- name: inboundCidrs
  objref:
    kind: ConfigMap
    name: istio-ingress-config
    apiVersion: v1
  fieldref:
    fieldpath: data.inboundCidrs
namespace: istio-system
configurations:
- params.yaml
