apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
<<<<<<< HEAD
<<<<<<< HEAD
resources:
- cache-deployer-role.yaml
- cache-deployer-rolebinding.yaml
- cache-deployer-deployment.yaml
images:
- name: gcr.io/ml-pipeline/cache-deployer
  newTag: 1.0.0
=======

resources:
  - cache-deployer-role.yaml
  - cache-deployer-rolebinding.yaml
  - cache-deployer-deployment.yaml
>>>>>>> 0dd7b24f049aaff540231bf73fe153c2397be890
=======
resources:
- cache-deployer-role.yaml
- cache-deployer-rolebinding.yaml
- cache-deployer-deployment.yaml
images:
- name: gcr.io/ml-pipeline/cache-deployer
  newTag: 1.0.4
>>>>>>> upstream/master
