apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../upstream/kfserving.yaml
- application.yaml
commonLabels:
  app: kfserving
  kustomize.component: kfserving
  app.kubernetes.io/component: kfserving
  app.kubernetes.io/name: kfserving
generatorOptions:
 disableNameSuffixHash: true
patchesStrategicMerge:
- configmap-patch.yaml
- statefulset-patch.yaml
