apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-pipeline-scheduledworkflow
spec:
  template:
    spec:
      containers:
      - name: ml-pipeline-scheduledworkflow
        resources:
          requests:
            cpu: 20m
            memory: 150Mi
          limits:
            cpu: 1
            memory: 1.5Gi