apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: metacontroller
spec:
  template:
    spec:
      containers:
      - name: metacontroller
        resources:
          requests:
            cpu: 500m
            memory: 1Gi
          limits:
            cpu: 4
            memory: 4Gi