apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
<<<<<<< HEAD:gcp/basic-auth-ingress/overlays/application/application.yaml
  name: basic-auth-ingress
=======
  labels:
    app.kubernetes.io/component: spartakus
    app.kubernetes.io/name: spartakus
  name: spartakus
  namespace: kubeflow
>>>>>>> upstream/master:tests/stacks/aws/application/spartakus/test_data/expected/app.k8s.io_v1beta1_application_spartakus.yaml
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: basic-auth-ingress
      app.kubernetes.io/instance: basic-auth-ingress-v1.0.0
      app.kubernetes.io/managed-by: kfctl
      app.kubernetes.io/component: basic-auth-ingress
      app.kubernetes.io/part-of: kubeflow
      app.kubernetes.io/version: v1.0.0
  componentKinds:
  - group: core
    kind: ConfigMap
  - group: apps
    kind: Deployment
  - group: core
    kind: ServiceAccount
  descriptor:
    type: basic-auth-ingress
    version: v1beta1
    description: ""
    maintainers: []
    owners: []
    keywords:
<<<<<<< HEAD:gcp/basic-auth-ingress/overlays/application/application.yaml
     - basic-auth-ingress
     - kubeflow
    links:
    - description: About
      url: ""
  addOwnerRef: true
=======
    - spartakus
    - kubeflow
    links:
    - description: About
      url: ""
    maintainers: []
    owners: []
    type: spartakus
    version: v1beta1
  selector:
    matchLabels:
      app.kubernetes.io/component: spartakus
      app.kubernetes.io/instance: spartakus-v0.7.0
      app.kubernetes.io/managed-by: kfctl
      app.kubernetes.io/name: spartakus
      app.kubernetes.io/part-of: kubeflow
      app.kubernetes.io/version: v0.7.0
>>>>>>> upstream/master:tests/stacks/aws/application/spartakus/test_data/expected/app.k8s.io_v1beta1_application_spartakus.yaml
