apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
<<<<<<< HEAD
<<<<<<< HEAD
=======
- minio-artifact-secret.yaml
>>>>>>> 0dd7b24f049aaff540231bf73fe153c2397be890
=======
>>>>>>> upstream/master
- workflow-controller-configmap.yaml
- workflow-controller-deployment.yaml
- workflow-controller-role.yaml
- workflow-controller-rolebinding.yaml
- workflow-controller-sa.yaml
