apiVersion: kfdef.apps.kubeflow.org/v1
kind: KfDef
metadata:
<<<<<<< HEAD
  name: kfctl-aws-cognito
=======
<<<<<<<< HEAD:kfdef/source/master/kfctl_aws_cognito.yaml
  name: kfctl-aws-cognito
========
  namespace: kubeflow
>>>>>>>> 0dd7b24f049aaff540231bf73fe153c2397be890:kfdef/kfctl_gcp_iap.yaml
>>>>>>> 0dd7b24f049aaff540231bf73fe153c2397be890
spec:
  applications:
  - kustomizeConfig:
      parameters:
      - name: namespace
        value: istio-system
      repoRef:
        name: manifests
<<<<<<< HEAD
<<<<<<< HEAD
        path: istio/istio-crds
=======
        path: istio-1-3-1/istio-crds-1-3-1
>>>>>>> 0dd7b24f049aaff540231bf73fe153c2397be890
=======
        path: istio/istio-crds
>>>>>>> upstream/master
    name: istio-crds
  - kustomizeConfig:
      parameters:
      - name: namespace
        value: istio-system
      repoRef:
        name: manifests
<<<<<<< HEAD
<<<<<<< HEAD
        path: istio/istio-install
=======
        path: istio-1-3-1/istio-install-1-3-1
>>>>>>> 0dd7b24f049aaff540231bf73fe153c2397be890
=======
        path: istio/istio-install
>>>>>>> upstream/master
    name: istio-install
  - kustomizeConfig:
      parameters:
      - name: namespace
        value: istio-system
      repoRef:
        name: manifests
<<<<<<< HEAD
<<<<<<< HEAD
=======
<<<<<<<< HEAD:kfdef/source/master/kfctl_aws_cognito.yaml
        path: istio-1-3-1/cluster-local-gateway-1-3-1
=======
        path: istio/cluster-local-gateway
>>>>>>> upstream/master
    name: cluster-local-gateway
  - kustomizeConfig:
      parameters:
========
>>>>>>> 0dd7b24f049aaff540231bf73fe153c2397be890
        path: istio/cluster-local-gateway
    name: cluster-local-gateway
  - kustomizeConfig:
      parameters:
<<<<<<< HEAD
      - name: clusterRbacConfig
        value: "ON"
=======
      - name: namespace
        value: istio-system
      repoRef:
        name: manifests
        path: istio/kfserving-gateway
    name: kfserving-gateway
  - kustomizeConfig:
      parameters:
>>>>>>>> 0dd7b24f049aaff540231bf73fe153c2397be890:kfdef/kfctl_gcp_iap.yaml
      - name: clusterRbacConfig
        value: 'ON'
>>>>>>> 0dd7b24f049aaff540231bf73fe153c2397be890
      repoRef:
        name: manifests
        path: istio/istio
    name: istio
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: application/application-crds
    name: application-crds
  - kustomizeConfig:
      overlays:
      - application
      repoRef:
        name: manifests
        path: application/application
    name: application
  - kustomizeConfig:
      parameters:
      - name: namespace
        value: cert-manager
<<<<<<< HEAD
=======
<<<<<<<< HEAD:kfdef/source/master/kfctl_aws_cognito.yaml
========
      repoRef:
        name: manifests
        path: cert-manager/cert-manager-crds
    name: cert-manager-crds
  - kustomizeConfig:
      parameters:
      - name: namespace
        value: kube-system
      repoRef:
        name: manifests
        path: cert-manager/cert-manager-kube-system-resources
    name: cert-manager-kube-system-resources
  - kustomizeConfig:
      overlays:
      - self-signed
      - application
      parameters:
      - name: namespace
        value: cert-manager
      repoRef:
        name: manifests
        path: cert-manager/cert-manager
    name: cert-manager
  - kustomizeConfig:
>>>>>>>> 0dd7b24f049aaff540231bf73fe153c2397be890:kfdef/kfctl_gcp_iap.yaml
>>>>>>> 0dd7b24f049aaff540231bf73fe153c2397be890
      repoRef:
        name: manifests
        path: cert-manager/cert-manager-crds
    name: cert-manager-crds
  - kustomizeConfig:
      parameters:
      - name: namespace
        value: kube-system
      repoRef:
        name: manifests
        path: cert-manager/cert-manager-kube-system-resources
    name: cert-manager-kube-system-resources
  - kustomizeConfig:
      overlays:
      - self-signed
      - application
      parameters:
      - name: namespace
        value: cert-manager
      repoRef:
        name: manifests
        path: cert-manager/cert-manager
    name: cert-manager
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: metacontroller
    name: metacontroller
  - kustomizeConfig:
      overlays:
      - istio
      - application
      repoRef:
        name: manifests
        path: argo
    name: argo
  - kustomizeConfig:
      repoRef:
        name: manifests
        path: kubeflow-roles
    name: kubeflow-roles
  - kustomizeConfig:
      overlays:
      - istio
      - application
      parameters:
      - name: userid-header
        value: kubeflow-userid
      repoRef:
        name: manifests
        path: common/centraldashboard
    name: centraldashboard
  - kustomizeConfig:
      overlays:
      - application
      repoRef:
        name: manifests
        path: admission-webhook/webhook
    name: webhook
  - kustomizeConfig:
      overlays:
      - application
      parameters:
      - name: webhookNamePrefix
        value: admission-webhook-
      repoRef:
        name: manifests
        path: admission-webhook/bootstrap
    name: bootstrap
  - kustomizeConfig:
      overlays:
      - istio
      - application
<<<<<<< HEAD
<<<<<<< HEAD
=======
      - aws
>>>>>>> 0dd7b24f049aaff540231bf73fe153c2397be890
=======
>>>>>>> upstream/master
      parameters:
      - name: userid-header
        value: kubeflow-userid
      repoRef:
        name: manifests
        path: jupyter/jupyter-web-app
    name: jupyter-web-app
  - kustomizeConfig:
      overlays:
      - application
      repoRef:
        name: manifests
        path: spark/spark-operator
    name: spark-operator
  - kustomizeConfig:
      overlays:
      - istio
      - application
      - db
      repoRef:
        name: manifests
        path: metadata
    name: metadata
  - kustomizeConfig:
      overlays:
      - istio
      - application
<<<<<<< HEAD
=======
<<<<<<<< HEAD:kfdef/source/master/kfctl_aws_cognito.yaml
========
      parameters:
      - name: injectGcpCredentials
        value: 'true'
>>>>>>>> 0dd7b24f049aaff540231bf73fe153c2397be890:kfdef/kfctl_gcp_iap.yaml
>>>>>>> 0dd7b24f049aaff540231bf73fe153c2397be890
      repoRef:
        name: manifests
        path: jupyter/notebook-controller
    name: notebook-controller
  - kustomizeConfig:
      overlays:
      - application
      repoRef:
        name: manifests
        path: pytorch-job/pytorch-job-crds
    name: pytorch-job-crds
  - kustomizeConfig:
      overlays:
      - application
      repoRef:
        name: manifests
        path: pytorch-job/pytorch-operator
    name: pytorch-operator
  - kustomizeConfig:
      overlays:
      - application
      parameters:
      - name: namespace
        value: knative-serving
      repoRef:
        name: manifests
        path: knative/knative-serving-crds
    name: knative-crds
  - kustomizeConfig:
      overlays:
      - application
      parameters:
      - name: namespace
        value: knative-serving
      repoRef:
        name: manifests
        path: knative/knative-serving-install
    name: knative-install
  - kustomizeConfig:
      overlays:
      - application
      repoRef:
        name: manifests
        path: kfserving/kfserving-crds
    name: kfserving-crds
  - kustomizeConfig:
      overlays:
      - application
      repoRef:
        name: manifests
        path: kfserving/kfserving-install
    name: kfserving-install
  - kustomizeConfig:
<<<<<<< HEAD
      parameters:
      - name: namespace
        value: istio-system
      repoRef:
        name: manifests
        path: istio/kfserving-gateway
    name: kfserving-gateway
  - kustomizeConfig:
=======
>>>>>>> 0dd7b24f049aaff540231bf73fe153c2397be890
      overlays:
      - application
      parameters:
      - name: usageId
<<<<<<< HEAD
        value: <randomly-generated-id>
      - name: reportUsage
        value: "true"
=======
<<<<<<<< HEAD:kfdef/source/master/kfctl_aws_cognito.yaml
        value: <randomly-generated-id>
========
        value: '7439583937720421527'
>>>>>>>> 0dd7b24f049aaff540231bf73fe153c2397be890:kfdef/kfctl_gcp_iap.yaml
      - name: reportUsage
        value: 'true'
>>>>>>> 0dd7b24f049aaff540231bf73fe153c2397be890
      repoRef:
        name: manifests
        path: common/spartakus
    name: spartakus
  - kustomizeConfig:
      overlays:
      - application
      repoRef:
        name: manifests
        path: tf-training/tf-job-crds
    name: tf-job-crds
  - kustomizeConfig:
      overlays:
      - application
      repoRef:
        name: manifests
        path: tf-training/tf-job-operator
    name: tf-job-operator
  - kustomizeConfig:
      overlays:
      - application
      repoRef:
        name: manifests
<<<<<<< HEAD
=======
        path: mxnet-job/mxnet-operator
    name: mxnet-operator
  - kustomizeConfig:
      overlays:
      - application
      repoRef:
        name: manifests
>>>>>>> 0dd7b24f049aaff540231bf73fe153c2397be890
        path: katib/katib-crds
    name: katib-crds
  - kustomizeConfig:
      overlays:
      - application
      - istio
      repoRef:
        name: manifests
        path: katib/katib-controller
    name: katib-controller
  - kustomizeConfig:
      overlays:
      - application
<<<<<<< HEAD
=======
      - use-kf-user
>>>>>>> 0dd7b24f049aaff540231bf73fe153c2397be890
      repoRef:
        name: manifests
        path: pipeline/api-service
    name: api-service
  - kustomizeConfig:
      overlays:
      - application
      parameters:
      - name: minioPvName
        value: minio-pv
      - name: minioPvcName
        value: minio-pv-claim
      repoRef:
        name: manifests
        path: pipeline/minio
    name: minio
  - kustomizeConfig:
      overlays:
      - application
      parameters:
      - name: mysqlPvName
        value: mysql-pv
      - name: mysqlPvcName
        value: mysql-pv-claim
      repoRef:
        name: manifests
        path: pipeline/mysql
    name: mysql
  - kustomizeConfig:
      overlays:
      - application
      repoRef:
        name: manifests
        path: pipeline/persistent-agent
    name: persistent-agent
  - kustomizeConfig:
      overlays:
      - application
<<<<<<< HEAD
=======
      - use-kf-user
>>>>>>> 0dd7b24f049aaff540231bf73fe153c2397be890
      repoRef:
        name: manifests
        path: pipeline/pipelines-runner
    name: pipelines-runner
  - kustomizeConfig:
      overlays:
      - istio
      - application
      repoRef:
        name: manifests
        path: pipeline/pipelines-ui
    name: pipelines-ui
  - kustomizeConfig:
      overlays:
      - application
      repoRef:
        name: manifests
        path: pipeline/pipelines-viewer
    name: pipelines-viewer
  - kustomizeConfig:
      overlays:
      - application
      repoRef:
        name: manifests
        path: pipeline/scheduledworkflow
    name: scheduledworkflow
  - kustomizeConfig:
      overlays:
      - application
<<<<<<< HEAD
=======
      - use-kf-user
>>>>>>> 0dd7b24f049aaff540231bf73fe153c2397be890
      repoRef:
        name: manifests
        path: pipeline/pipeline-visualization-service
    name: pipeline-visualization-service
  - kustomizeConfig:
      overlays:
      - application
      - istio
      parameters:
<<<<<<< HEAD
=======
<<<<<<<< HEAD:kfdef/source/master/kfctl_aws_cognito.yaml
========
      - name: admin
>>>>>>>> 0dd7b24f049aaff540231bf73fe153c2397be890:kfdef/kfctl_gcp_iap.yaml
>>>>>>> 0dd7b24f049aaff540231bf73fe153c2397be890
      - name: userid-header
        value: kubeflow-userid
      repoRef:
        name: manifests
        path: profiles
    name: profiles
  - kustomizeConfig:
      overlays:
      - application
      repoRef:
        name: manifests
        path: seldon/seldon-core-operator
    name: seldon-core
  - kustomizeConfig:
      overlays:
      - application
      repoRef:
        name: manifests
        path: mpi-job/mpi-operator
    name: mpi-operator
  - kustomizeConfig:
      overlays:
      - cognito
      parameters:
      - name: namespace
        value: istio-system
<<<<<<< HEAD
=======
<<<<<<<< HEAD:kfdef/source/master/kfctl_aws_cognito.yaml
========
      - name: ipName
        value: test1-ip
      - name: hostname
>>>>>>>> 0dd7b24f049aaff540231bf73fe153c2397be890:kfdef/kfctl_gcp_iap.yaml
>>>>>>> 0dd7b24f049aaff540231bf73fe153c2397be890
      repoRef:
        name: manifests
        path: aws/istio-ingress
    name: istio-ingress
  - kustomizeConfig:
      overlays:
      - application
      parameters:
      - name: namespace
        value: istio-system
      - name: origin-header
        value: x-amzn-oidc-data
      - name: custom-header
        value: kubeflow-userid
      repoRef:
        name: manifests
        path: aws/aws-istio-authz-adaptor
    name: aws-istio-authz-adaptor
  - kustomizeConfig:
      overlays:
      - application
      parameters:
<<<<<<< HEAD
=======
<<<<<<<< HEAD:kfdef/source/master/kfctl_aws_cognito.yaml
>>>>>>> 0dd7b24f049aaff540231bf73fe153c2397be890
      - name: clusterName
        value: kubeflow-aws
      repoRef:
        name: manifests
        path: aws/aws-alb-ingress-controller
    name: aws-alb-ingress-controller
  - kustomizeConfig:
      overlays:
      - application
<<<<<<< HEAD
=======
========
      - name: user
      - name: profile-name
        value: anonymous
>>>>>>>> 0dd7b24f049aaff540231bf73fe153c2397be890:kfdef/kfctl_gcp_iap.yaml
>>>>>>> 0dd7b24f049aaff540231bf73fe153c2397be890
      repoRef:
        name: manifests
        path: aws/nvidia-device-plugin
    name: nvidia-device-plugin
  plugins:
  - kind: KfAwsPlugin
    metadata:
      name: aws
    spec:
<<<<<<< HEAD
=======
<<<<<<<< HEAD:kfdef/source/master/kfctl_aws_cognito.yaml
>>>>>>> 0dd7b24f049aaff540231bf73fe153c2397be890
      auth:
        cognito:
          certArn: arn:aws:acm:us-west-2:xxxxx:certificate/xxxxxxxxxxxxx-xxxx
          cognitoAppClientId: xxxxxbxxxxxx
          cognitoUserPoolArn: arn:aws:cognito-idp:us-west-2:xxxxx:userpool/us-west-2_xxxxxx
          cognitoUserPoolDomain: your-user-pool
      region: us-west-2
<<<<<<< HEAD
      roles:
      - eksctl-kubeflow-aws-nodegroup-ng-a2-NodeInstanceRole-xxxxx
=======
      enablePodIamPolicy: true
      # If you don't use IAM Role for Service Account, you can still use node instance roles.
      #roles:
      #- eksctl-kubeflow-aws-nodegroup-ng-a2-NodeInstanceRole-xxxxxxx
========
      createPipelinePersistentStorage: true
      deploymentManagerConfig:
        repoRef:
          name: manifests
          path: gcp/deployment_manager_configs
      enableWorkloadIdentity: true
      skipInitProject: true
      useBasicAuth: false
>>>>>>>> 0dd7b24f049aaff540231bf73fe153c2397be890:kfdef/kfctl_gcp_iap.yaml
>>>>>>> 0dd7b24f049aaff540231bf73fe153c2397be890
  repos:
  - name: manifests
    uri: https://github.com/kubeflow/manifests/archive/master.tar.gz
  version: master
