apiVersion: apps/v1
kind: Deployment
metadata:
  name: seldon-controller-manager
  namespace: 'kubeflow'
spec:
  template:
    spec:
      containers:
      - name: manager
        resources:
          requests:
            cpu: 100m
            memory: 20Mi
          limits:
            cpu: 100m
            memory: 30Mi