apiVersion: apps/v1
kind: Deployment
metadata:
  name: ml-pipeline-ui
spec:
  template:
    spec:
      containers:
      - name: ml-pipeline-ui
        resources:
          requests:
            cpu: 20m
            memory: 100Mi
          limits:
            cpu: 1
            memory: 1Gi