apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kfserving-controller-manager
spec:
  template:
    spec:
      containers:
      - name: kube-rbac-proxy
        resources:
          requests:
            cpu: 10m
            memory: 40Mi
          limits:
            cpu: 1
            memory: 400Mi
      - name: manager
        resources:
          requests:
            cpu: 100m
            memory: 200Mi
          limits:
            cpu: 100m
            memory: 300Mi  