apiVersion: apps/v1
kind: Deployment
metadata:
  name: tensorboard
spec:
  template:
    spec:
      containers:
      - name: tensorboard
        resources:
          requests:
            cpu: 1
            memory: 1Gi
          limits:
            cpu: 4
            memory: 4Gi