apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
  labels:
    notebook: controller
    name: notebook-controller-deployment
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      notebook: controller
  template:
    metadata:
      name: notebook-controller
      labels:
        notebook: controller
    spec:
      containers:
      - name: notebook-controller
        image: tmaxcloudck/notebook-controller-go:b0.0.2
        imagePullPolicy: Always
      serviceAccountName: service-account
