apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: hypercloud4-admin
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: deployment
spec:
    template:
    spec:
        containers:
        - name: notebook-controller
        env:
            - name: ISTIO_GATEWAY
            value: $(ISTIO_GATEWAY)