apiVersion: apps/v1
kind: Deployment
metadata:
    name: deployment
spec:
    template:
    spec:
        containers:
        - name: notebook-controller
        env:
            - name: ISTIO_GATEWAY
            value: $(ISTIO_GATEWAY)