apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
spec:
  template:
    spec:
      containers:
      - name: notebook-controller
        env:
          - name: USE_ISTIO
            valueFrom:
              configMapKeyRef:
                name: notebook-controller-config
                key: USE_ISTIO
          - name: ISTIO_GATEWAY
            valueFrom:
              configMapKeyRef:
                name: notebook-controller-config
                key: ISTIO_GATEWAY
        