apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: stateful-set
spec:
  template:
    spec:
      containers:
      - name: manager
        resources:
          requests:
            cpu: 70m
            memory: 200Mi
          limits:
            cpu: 1
            memory: 2Gi