---
apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metadata:
  name: ck-selfsigned-clusterissuer
  labels:
    some-annotation: "true"
spec:
  selfSigned: {} 
--- 
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: selfsigned-cert-example
  namespace: kubeflow
  labels:
    some-annotation: "true"
spec:
  secretName: hypercloud-workflow-webhook-certs
  duration: 2880h
  renewBefore: 360h
  dnsNames:
    - hypercloud-workflow-webhook-svc.kubeflow.svc
    - hypercloud-workflow-webhook-svc.kubeflow.svc.cluster.local
    - hypercloud-workflowtemplate-webhook-svc.kubeflow.svc
    - hypercloud-workflowtemplate-webhook-svc.kubeflow.svc.cluster.local
    - hypercloud-workflow-webhook-svc
    - hypercloud-workflowtemplate-webhook-svc
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - digital signature
    - key encipherment
    - server auth
  issuerRef:
    name: ck-selfsigned-clusterissuer
    kind: ClusterIssuer
    group: cert-manager.io
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: hypercloud-workflow-webhook-mutator
  annotations:
    cert-manager.io/inject-ca-from: argo/selfsigned-cert-example
webhooks:
- admissionReviewVersions:
  - v1beta1
  clientConfig:
    service:
      name: hypercloud-workflow-webhook-svc
      namespace: kubeflow
      path: /api/webhook/add-serviceaccount/workflow 
      port: 443
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: hypercloud-workflow-webhook-svc.kubeflow.svc
  namespaceSelector:
    matchExpressions:
    - key: workflow-webhook
      operator: NotIn
      values:
      - "false"
  objectSelector: {}
  reinvocationPolicy: Never
  rules:
  - apiGroups:
    - argoproj.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - workflows
    scope: '*'
  sideEffects: None
  timeoutSeconds: 10
- admissionReviewVersions:
  - v1beta1
  clientConfig:
    service:
      name: hypercloud-workflowtemplate-webhook-svc
      namespace: kubeflow
      path: /api/webhook/add-serviceaccount/workflowtemplate
      port: 443
  failurePolicy: Fail
  matchPolicy: Equivalent
  name: hypercloud-workflowtemplate-webhook-svc.kubeflow.svc
  namespaceSelector:
    matchExpressions:
    - key: workflow-webhook
      operator: NotIn
      values:
      - "false"
  objectSelector: {}
  reinvocationPolicy: Never
  rules:
  - apiGroups:
    - argoproj.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - workflowtemplates
    scope: '*'
  sideEffects: None
  timeoutSeconds: 10
---
apiVersion: apps/v1
kind: Deployment
metadata:
  generation: 1
  labels:
    hypercloud: workflow-webhook
  name: hypercloud-workflow-webhook
  namespace: kubeflow
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      hypercloud: workflow-webhook
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        hypercloud: workflow-webhook
    spec:
      serviceAccountName: default
      containers:
      - env:
        - name: TZ
          value: Asia/Seoul
        image: atcham/test:v2.3.10
        imagePullPolicy: Always
        name: hypercloud-workflow-webhook
        ports:
        - containerPort: 8443
          name: webhook
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
          requests:
            cpu: 500m
            memory: 1Gi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /run/secrets/tls
          name: hypercloud-workflow-webhook-certs
          readOnly: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: hypercloud-workflow-webhook-certs
        secret:
          defaultMode: 420
          secretName: hypercloud-workflow-webhook-certs
---
apiVersion: v1
kind: Service
metadata:
  labels:
    hypercloud: workflow-webhook
  name: hypercloud-workflow-webhook-svc
  namespace: kubeflow
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: webhook
  selector:
    hypercloud: workflow-webhook
  sessionAffinity: None
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  labels:
    hypercloud: workflow-webhook
  name: hypercloud-workflowtemplate-webhook-svc
  namespace: kubeflow
spec:
  ports:
  - port: 443
    protocol: TCP
    targetPort: webhook
  selector:
    hypercloud: workflow-webhook
  sessionAffinity: None
  type: ClusterIP
